In [2]:
import pandas as pd
import numpy as np

In [3]:
qptm = pd.read_csv('/home/amaqueda/TFM/ML_project/PTM_sites/input/qPTM/qPTM_human_sites.tsv', sep = '\t', header = 0)
qptm.shape

(5389086, 16)

In [21]:
# Keep good quality sites (stars > 4)
stars = qptm[qptm.Reliability >= 4]
print(stars.shape)
stars.head()

(4550892, 16)

,Organism,PMID,UniProt accession,Gene name,Position,PTM,Sequence window,Raw peptide,Sample,Condition,Log2Ratio (peptide),P value (peptide),Log2Ratio (protein),P value (protein),Reliability,fdr (peptide)
0,Human,28188228,P04075,ALDOA,39,Phosphorylation,AADESTGSIAKRLQS,GILAADESTGsIAKR,COLO 205,PLX4032 15min/Ctr,-0.375,-,-,-,5,0
1,Human,29214152,P07814,EPRS1,999,Phosphorylation,NQGGGLSSSGAGEGQ,RKDPSKNQGGGLSsSGAGEGQGPKK,HeLa,CX-4945/Ctr,-0.069,-,-,-,5,0.000215537
2,Human,24850871,Q09666,AHNAK,3483,Phosphorylation,KMKMPKFSVSGLKAE,FsVSGLKAEGPDVAVDLPK,Jurkat,PGE2 20min/Ctr,0.016,0.736,-,-,5,0.000189075
3,Human,22199227,Q09666,AHNAK,5400,Phosphorylation,SLEASEGSIKLPKMK,VSVGAPDLSLEASEGsIK,hTERT-RPE1,Plk1(wt) 3-MB-PP1/Ctr,0.077,0.008,0.01,-,5,0
5,Human,24117733,Q9UKI2,CDC42EP3,108,Phosphorylation,PVLKNAISLPTIGGS,NAIsLPTIGGSQALMLPLLSPVTFNSK,SH-SY5Y,LRRK2-IN-1/Ctr,-2.219,0.207,-,-,5,0.000599017

In [19]:
# As qPTM has proteomics data, drop duplicates to keep only the site
sites = stars[['Gene name','Position','PTM','Sequence window','UniProt accession']].drop_duplicates()
sites.head()

  Gene name  Position              PTM  Sequence window UniProt accession
0     ALDOA        39  Phosphorylation  AADESTGSIAKRLQS            P04075
1     EPRS1       999  Phosphorylation  NQGGGLSSSGAGEGQ            P07814
2     AHNAK      3483  Phosphorylation  KMKMPKFSVSGLKAE            Q09666
3     AHNAK      5400  Phosphorylation  SLEASEGSIKLPKMK            Q09666
5  CDC42EP3       108  Phosphorylation  PVLKNAISLPTIGGS            Q9UKI2

In [32]:
sites.shape

(85457, 5)

In [33]:
#All sites have +- 7 region
all([len(i) == 15 for i in sites['Sequence window']])

True

In [38]:
sites['residue'] = [seq[7] for seq in sites['Sequence window'].tolist()]
print(sites.shape)
sites.head()

(85457, 6)

,Gene name,Position,PTM,Sequence window,UniProt accession,residue
0,ALDOA,39,Phosphorylation,AADESTGSIAKRLQS,P04075,S
1,EPRS1,999,Phosphorylation,NQGGGLSSSGAGEGQ,P07814,S
2,AHNAK,3483,Phosphorylation,KMKMPKFSVSGLKAE,Q09666,S
3,AHNAK,5400,Phosphorylation,SLEASEGSIKLPKMK,Q09666,S
5,CDC42EP3,108,Phosphorylation,PVLKNAISLPTIGGS,Q9UKI2,S

In [41]:
sites.to_csv('/home/amaqueda/TFM/ML_project/PTM_sites/output/qPTM/qPTM.clean.tsv', sep = '\t', index = False)

In [4]:
sites = pd.read_csv('/home/amaqueda/TFM/ML_project/PTM_sites/output/qPTM/qPTM.clean.tsv', sep = '\t', header = 0)
sites

,Gene name,Position,PTM,Sequence window,UniProt accession,residue
0,ALDOA,39,Phosphorylation,AADESTGSIAKRLQS,P04075,S
1,EPRS1,999,Phosphorylation,NQGGGLSSSGAGEGQ,P07814,S
2,AHNAK,3483,Phosphorylation,KMKMPKFSVSGLKAE,Q09666,S
3,AHNAK,5400,Phosphorylation,SLEASEGSIKLPKMK,Q09666,S
4,CDC42EP3,108,Phosphorylation,PVLKNAISLPTIGGS,Q9UKI2,S
...,...,...,...,...,...,...
85452,FOSL2,222,Acetylation,SVGAVVVKQEPLEED,P15408,K
85453,MAPRE1,148,Acetylation,LVAPALNKPKKPLTS,Q15691,K
85454,CCNO,8,Phosphorylation,MVTPCPTSPSSPAAR,P22674,S
85455,ZNF826P,115,Phosphorylation,HKHRRTHTGEKPYKC,Q6ZT77,T
85456,NBN,544,Acetylation,SKSHAAEKLRSNKKR,O60934,K

In [6]:
sites[['Gene name','Position','PTM']].drop_duplicates()

      Gene name  Position              PTM
0         ALDOA        39  Phosphorylation
1         EPRS1       999  Phosphorylation
2         AHNAK      3483  Phosphorylation
3         AHNAK      5400  Phosphorylation
4      CDC42EP3       108  Phosphorylation
...         ...       ...              ...
85452     FOSL2       222      Acetylation
85453    MAPRE1       148      Acetylation
85454      CCNO         8  Phosphorylation
85455   ZNF826P       115  Phosphorylation
85456       NBN       544      Acetylation

[85401 rows x 3 columns]